[2023-03-29T12:47:59.116+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T12:25:00+00:00 [queued]>
[2023-03-29T12:47:59.151+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T12:25:00+00:00 [queued]>
[2023-03-29T12:47:59.152+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T12:47:59.154+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T12:47:59.156+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T12:47:59.216+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): model_predict> on 2023-03-29 12:25:00+00:00
[2023-03-29T12:47:59.239+0000] {standard_task_runner.py:55} INFO - Started process 1982 to run task
[2023-03-29T12:47:59.267+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'model_predict', 'scheduled__2023-03-29T12:25:00+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpkh2mk714']
[2023-03-29T12:47:59.286+0000] {standard_task_runner.py:83} INFO - Job 380: Subtask model_predict
[2023-03-29T12:47:59.535+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.model_predict scheduled__2023-03-29T12:25:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T12:47:59.923+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=model_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T12:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T12:25:00+00:00
[2023-03-29T12:48:02.596+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T12:48:10.016+0000] {gbq.py:352} INFO - Total time taken 9.91 s.
Finished at 2023-03-29 12:48:10.
[2023-03-29T12:48:10.026+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 154, in model_predict
    dag=dag,
ModuleNotFoundError: No module named 'lightgbm'
[2023-03-29T12:48:10.062+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=model_predict, execution_date=20230329T122500, start_date=20230329T124759, end_date=20230329T124810
[2023-03-29T12:48:10.115+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 380 for task model_predict (No module named 'lightgbm'; 1982)
[2023-03-29T12:48:10.202+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T12:48:10.237+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
