[2023-03-29T23:16:21.993+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tax_income.model_predict manual__2023-03-29T23:12:48.558725+00:00 [queued]>
[2023-03-29T23:16:22.018+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tax_income.model_predict manual__2023-03-29T23:12:48.558725+00:00 [queued]>
[2023-03-29T23:16:22.020+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T23:16:22.022+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-03-29T23:16:22.024+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T23:16:22.052+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): model_predict> on 2023-03-29 23:12:48.558725+00:00
[2023-03-29T23:16:22.065+0000] {standard_task_runner.py:55} INFO - Started process 288 to run task
[2023-03-29T23:16:22.073+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tax_income', 'model_predict', 'manual__2023-03-29T23:12:48.558725+00:00', '--job-id', '569', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp8_papczm']
[2023-03-29T23:16:22.078+0000] {standard_task_runner.py:83} INFO - Job 569: Subtask model_predict
[2023-03-29T23:16:22.194+0000] {task_command.py:388} INFO - Running <TaskInstance: tax_income.model_predict manual__2023-03-29T23:12:48.558725+00:00 [running]> on host 32688d23169d
[2023-03-29T23:16:22.351+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tax_income
AIRFLOW_CTX_TASK_ID=model_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T23:12:48.558725+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T23:12:48.558725+00:00
[2023-03-29T23:16:22.355+0000] {test.py:130} INFO - Loading data from BigQuery...
[2023-03-29T23:16:24.095+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T23:16:34.483+0000] {gbq.py:352} INFO - Total time taken 11.94 s.
Finished at 2023-03-29 23:16:34.
[2023-03-29T23:16:34.485+0000] {test.py:145} INFO - One-hot encoding categorical features...
[2023-03-29T23:16:34.589+0000] {test.py:151} INFO - Loading XGBoost model and performing predictions...
[2023-03-29T23:16:34.609+0000] {logging_mixin.py:137} INFO - [23:16:34] WARNING: ../src/learner.cc:749: Found JSON model saved before XGBoost 1.6, please save the model using current version again. The support for old JSON model will be discontinued in XGBoost 2.3.
[2023-03-29T23:16:35.117+0000] {test.py:157} INFO - Adding predictions to DataFrame...
[2023-03-29T23:16:35.120+0000] {test.py:162} INFO - Exporting DataFrame to BigQuery...
[2023-03-29T23:16:37.661+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 174, in model_predict
    {'name':'predictions','type': 'STRING'}
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 1205, in to_gbq
    billing_project=project_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/gbq.py", line 599, in load_data
    billing_project=billing_project,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/load.py", line 246, in load_chunks
    billing_project=billing_project,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas_gbq/load.py", line 136, in load_parquet
    project=billing_project,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 2675, in load_table_from_dataframe
    parquet_use_compliant_nested_type=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 586, in dataframe_to_parquet
    arrow_table = dataframe_to_arrow(dataframe, bq_schema)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 529, in dataframe_to_arrow
    bq_to_arrow_array(get_column_or_index(dataframe, bq_field.name), bq_field)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 290, in bq_to_arrow_array
    return pyarrow.Array.from_pandas(series, type=arrow_type)
  File "pyarrow/array.pxi", line 1037, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 313, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Expected a string or bytes dtype, got float32
[2023-03-29T23:16:37.708+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=tax_income, task_id=model_predict, execution_date=20230329T231248, start_date=20230329T231621, end_date=20230329T231637
[2023-03-29T23:16:37.736+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 569 for task model_predict (Expected a string or bytes dtype, got float32; 288)
[2023-03-29T23:16:37.835+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T23:16:37.886+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
