[2023-03-29T12:51:30.292+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T12:45:00+00:00 [queued]>
[2023-03-29T12:51:30.317+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T12:45:00+00:00 [queued]>
[2023-03-29T12:51:30.319+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T12:51:30.320+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T12:51:30.323+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T12:51:30.372+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): model_predict> on 2023-03-29 12:45:00+00:00
[2023-03-29T12:51:30.392+0000] {standard_task_runner.py:55} INFO - Started process 2050 to run task
[2023-03-29T12:51:30.398+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'model_predict', 'scheduled__2023-03-29T12:45:00+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpfhr08uov']
[2023-03-29T12:51:30.407+0000] {standard_task_runner.py:83} INFO - Job 383: Subtask model_predict
[2023-03-29T12:51:30.578+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.model_predict scheduled__2023-03-29T12:45:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T12:51:30.780+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=model_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T12:45:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T12:45:00+00:00
[2023-03-29T12:51:33.683+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T12:51:42.906+0000] {gbq.py:352} INFO - Total time taken 11.97 s.
Finished at 2023-03-29 12:51:42.
[2023-03-29T12:51:42.911+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 147, in model_predict
    model=pickle.load(open('/opt/airflow/data/model.pkl','rb'))
ModuleNotFoundError: No module named 'lightgbm'
[2023-03-29T12:51:42.932+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=model_predict, execution_date=20230329T124500, start_date=20230329T125130, end_date=20230329T125142
[2023-03-29T12:51:42.960+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 383 for task model_predict (No module named 'lightgbm'; 2050)
[2023-03-29T12:51:43.039+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T12:51:43.068+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
