[2023-03-30T07:00:23.766+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tax_income.extract_and_load scheduled__2023-03-29T05:00:00+00:00 [queued]>
[2023-03-30T07:00:23.790+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tax_income.extract_and_load scheduled__2023-03-29T05:00:00+00:00 [queued]>
[2023-03-30T07:00:23.792+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T07:00:23.793+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-30T07:00:23.794+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T07:00:23.826+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-03-29 05:00:00+00:00
[2023-03-30T07:00:23.839+0000] {standard_task_runner.py:55} INFO - Started process 1519 to run task
[2023-03-30T07:00:23.847+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tax_income', 'extract_and_load', 'scheduled__2023-03-29T05:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_model.py', '--cfg-path', '/tmp/tmplv_j1zbc']
[2023-03-30T07:00:23.852+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask extract_and_load
[2023-03-30T07:00:24.035+0000] {task_command.py:388} INFO - Running <TaskInstance: tax_income.extract_and_load scheduled__2023-03-29T05:00:00+00:00 [running]> on host d8c38a1ae850
[2023-03-30T07:00:24.264+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tax_income
AIRFLOW_CTX_TASK_ID=extract_and_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T05:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T05:00:00+00:00
[2023-03-30T07:00:24.268+0000] {dag_model.py:67} INFO - Starting load_csv_from_bucket function...
[2023-03-30T07:00:24.418+0000] {dag_model.py:76} INFO - Downloading CSV files from test-chr-ml 
[2023-03-30T09:10:25.437+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_model.py", line 84, in load_csv_from_bucket
    blob.download_to_filename("/tmp/" + filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1270, in download_to_filename
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 1096, in download_blob_to_file
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 984, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 238, in consume
    retriable_request, self._get_status_code, self._retry_strategy
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/_request_helpers.py", line 148, in wait_and_retry
    response = func()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 233, in retriable_request
    self._write_to_stream(result)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 141, in _write_to_stream
    raise common.DataCorruption(response, msg)
google.resumable_media.common.DataCorruption: Checksum mismatch while downloading:

  https://storage.googleapis.com/download/storage/v1/b/test-chr-ml/o/primary%2Fdata.csv%2Fcensus_income_learn.csv?generation=1679778413585655&alt=media

The X-Goog-Hash header indicated an MD5 checksum of:

  iH9NxBCpm8MyvduwpBlbiA==

but the actual MD5 checksum of the downloaded contents was:

  x/Ciao8wXVwQAOuyLhLAcA==

[2023-03-30T09:10:25.489+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=tax_income, task_id=extract_and_load, execution_date=20230329T050000, start_date=20230330T070023, end_date=20230330T091025
[2023-03-30T09:10:25.545+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task extract_and_load (Checksum mismatch while downloading:

  https://storage.googleapis.com/download/storage/v1/b/test-chr-ml/o/primary%2Fdata.csv%2Fcensus_income_learn.csv?generation=1679778413585655&alt=media

The X-Goog-Hash header indicated an MD5 checksum of:

  iH9NxBCpm8MyvduwpBlbiA==

but the actual MD5 checksum of the downloaded contents was:

  x/Ciao8wXVwQAOuyLhLAcA==
; 1519)
[2023-03-30T09:10:25.681+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-30T09:10:25.767+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-30T11:19:57.288+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tax_income.extract_and_load scheduled__2023-03-29T05:00:00+00:00 [queued]>
[2023-03-30T11:19:57.345+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tax_income.extract_and_load scheduled__2023-03-29T05:00:00+00:00 [queued]>
[2023-03-30T11:19:57.348+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T11:19:57.351+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-30T11:19:57.353+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-30T11:19:57.412+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): extract_and_load> on 2023-03-29 05:00:00+00:00
[2023-03-30T11:19:57.447+0000] {standard_task_runner.py:55} INFO - Started process 133 to run task
[2023-03-30T11:19:57.476+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tax_income', 'extract_and_load', 'scheduled__2023-03-29T05:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_model.py', '--cfg-path', '/tmp/tmptp1fq0a4']
[2023-03-30T11:19:57.600+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask extract_and_load
[2023-03-30T11:19:58.689+0000] {task_command.py:388} INFO - Running <TaskInstance: tax_income.extract_and_load scheduled__2023-03-29T05:00:00+00:00 [running]> on host d8c38a1ae850
[2023-03-30T11:20:01.407+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tax_income
AIRFLOW_CTX_TASK_ID=extract_and_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T05:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T05:00:00+00:00
[2023-03-30T11:20:01.425+0000] {dag_model.py:67} INFO - Starting load_csv_from_bucket function...
[2023-03-30T11:20:02.063+0000] {dag_model.py:76} INFO - Downloading CSV files from test-chr-ml 
