[2023-03-29T16:15:38.763+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T16:10:00+00:00 [queued]>
[2023-03-29T16:15:38.790+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.model_predict scheduled__2023-03-29T16:10:00+00:00 [queued]>
[2023-03-29T16:15:38.792+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T16:15:38.795+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-29T16:15:38.797+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T16:15:38.835+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): model_predict> on 2023-03-29 16:10:00+00:00
[2023-03-29T16:15:38.851+0000] {standard_task_runner.py:55} INFO - Started process 3619 to run task
[2023-03-29T16:15:38.862+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'model_predict', 'scheduled__2023-03-29T16:10:00+00:00', '--job-id', '430', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp_7z2szsi']
[2023-03-29T16:15:38.867+0000] {standard_task_runner.py:83} INFO - Job 430: Subtask model_predict
[2023-03-29T16:15:39.027+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.model_predict scheduled__2023-03-29T16:10:00+00:00 [running]> on host e7ec0deaf382
[2023-03-29T16:15:39.252+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=model_predict
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T16:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-29T16:10:00+00:00
[2023-03-29T16:15:47.980+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/google/cloud/bigquery/table.py:1988: UserWarning: A progress bar was requested, but there was an error loading the tqdm library. Please install tqdm to use the progress bar functionality.
  create_bqstorage_client=create_bqstorage_client,

[2023-03-29T16:16:01.729+0000] {gbq.py:352} INFO - Total time taken 22.26 s.
Finished at 2023-03-29 16:16:01.
[2023-03-29T16:16:01.891+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 121, in model_predict
    model=pickle.load(open('/opt/airflow/data/model.pkl','rb'))
ModuleNotFoundError: No module named 'lightgbm'
[2023-03-29T16:16:01.910+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=my_dag, task_id=model_predict, execution_date=20230329T161000, start_date=20230329T161538, end_date=20230329T161601
[2023-03-29T16:16:01.944+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 430 for task model_predict (No module named 'lightgbm'; 3619)
[2023-03-29T16:16:02.080+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-29T16:16:02.123+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
